### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dhiana** [kmmbvnr/django-jenkins#188]
Running jenkins management command with sloccount task was raising the following non-friendly unintuitive error:

OSError: [Errno 2] No such file or directory

But the issue here was that sloccount wasn't installed on my new machine.

Maybe raising a more appropriate error would be better.

**Comment by jinxac** [comment]
Is the issue fixed? I can still see this now too. I did following:-

1. Installed using brew, `brew install sloccount`
2. Forgot to link
3. Ran the `python manage.py jenkins  --settings=project_name.test_settings --enable-coverage`

Ideally it should have thrown proper error message like above but still I got following:-

```
Executing django_jenkins.tasks.run_sloccount...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 116, in handle
    coverage.save(tested_locations, options)
  File "/Users/aragorn/insights/venv/lib/python2.7/site-packages/django_jenkins/tasks/run_sloccount.py", line 11, in run
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Once I linked using `brew link sloccount`, it works fine.
