### ISSUE TITLE
Django 1.8 argparse error:  conflicting option string(s): --debug

### ISSUE THREAD

**Issue by nikolas2** [kmmbvnr/django-jenkins#282]
Using django-jenkins 0.17.0 with Django 1.8, I get this stack trace:

```
./manage.py jenkins --pep8-exclude=migrations --enable-coverage --coverage-rcfile=.coveragerc
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 110, in create_parser
    parser = super(Command, self).create_parser(prog_name, subcommand)
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 351, in create_parser
    self.add_arguments(parser)
  File "/home/nnyby/src/dmt/ve/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 87, in add_arguments
    help='Do not intercept stdout and stderr, friendly for console debuggers'),
  File "/usr/lib/python2.7/argparse.py", line 1301, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1675, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1502, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1315, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1453, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -l/--debug: conflicting option string(s): --debug
Makefile:31: recipe for target 'test' failed
make: *** [test] Error 1
```

https://travis-ci.org/ccnmtl/dmt/builds/58805997#L1020

**Comment by kmmbvnr** [comment]
That's actually strange. Do you have custom testrunner that adds the --debug option?

Django itself have no --debug option in its own codebase.

Could you debug to see from where --debug option cames?

**Comment by kmmbvnr** [comment]
I lol'd. You have:

   TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

**Comment by nikolas2** [comment]
What should `TEST_RUNNER` be set to?

**Comment by kmmbvnr** [comment]
Nope, django-jenkis is not require django-nose.

**Comment by nikolas2** [comment]
Thanks. I left a note about this error on the django-nose branch that I was using this with: https://github.com/django-nose/django-nose/pull/196
