### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'csslint'

### ISSUE THREAD

**Issue by jspitzen** [kmmbvnr/django-jenkins#290]
I am trying to report violations in my css files. I have pylint installed (1.4.3), and in my settings.py I have:
```
JENKINS_TASKS = (
    'django_jenkins.tasks.run_pep8',
    'django_jenkins.tasks.run_csslint',
)
```

Pep8 works fine, but when i run `python manage.py jenkins`, i get:
```
Executing django_jenkins.tasks.run_csslint...
Traceback (most recent call last):
  File "main/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django_jenkins/management/commands/jenkins.py", line 161, in handle
    coverage.save(tested_locations, options)
  File "/var/lib/jenkins/shiningpanda/jobs/0014326d/virtualenvs/d41d8cd9/lib/python3.4/site-packages/django_jenkins/tasks/run_csslint.py", line 43, in run
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'csslint'
```

Relevant portions of `pip list`:
```
coverage (3.7.1)
Django (1.8.2)
django-jenkins (0.17.0)
pep8 (1.6.2)
pip (1.5.6)
pyflakes (0.8.1)
pylint (1.4.3)

```

**Comment by kmmbvnr** [comment]
You need to install csslint tool. Read the docs, please.

**Comment by jspitzen** [comment]
The docs say "You should have the pylint package installed"

**Comment by kmmbvnr** [comment]
Mm, yeh. May be some merge bug.

You need csslint. It's the npm package.

**Comment by jspitzen** [comment]
Okay, thanks!
