### ISSUE TITLE
Version 0.14.0 is broken because it pulls coverage 4.0

### ISSUE THREAD

**Issue by ksolademi** [kmmbvnr/django-jenkins#304]
After newly installing **django-jenkins==0.14.0** running **manage.py jenkins --verbosity=2** results in the following traceback:
```
ImportError when trying to import dev
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 70, in load_command_class
    return module.Command()
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django_jenkins/management/commands/__init__.py", line 54, in __init__
    self.tasks_cls = [import_module(module_name).Task for module_name in self.get_task_list()]
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/srv/workspace/item_management_system_develop/virtualenv/local/lib/python2.7/site-packages/django_jenkins/tasks/with_coverage.py", line 5, in <module>
    from coverage.control import coverage
ImportError: cannot import name coverage
```
In django-jenkins requirements file I see the coverage requirement is specified as **coverage>=3.4.** Looks like coverage 4.0 introduced some breaking changes.

**Comment by NotSqrt** [comment]
It's fixed in current master : #301

**Comment by ksolademi** [comment]
Okay, just wasn't sure how much support the older versions get. Master doesn't support django 1.4, and so I was kind of stuck with this one.

Not a huge problem though, as I work around it by requiring an older version of coverage after requirement line for django-jenkins.

**Comment by NotSqrt** [comment]
Django 1.4 long term support just ended ... So I suppose not too many apps will continue to support it..
