### ISSUE TITLE
coverage.save breaks build when not using coverage

### ISSUE THREAD

**Issue by danchalmers** [kmmbvnr/django-jenkins#312]
I have a purely pep8 django-jenkins step, run as:
./manage.py jenkins --pep8-exclude="**/migrations/*"
but for testing I can run against one app and get the same effect with:
./manage.py jenkins story

The relevant settings say:
INSTALLED_APPS = INSTALLED_APPS + (
    'django_jenkins',
)
JENKINS_TASKS = (
    'django_jenkins.tasks.run_pep8',
    # 'django_jenkins.tasks.run_pylint',
    # 'django_jenkins.tasks.run_pyflakes',
    # 'django_jenkins.tasks.run_jslint',
    # 'django_jenkins.tasks.run_csslint',
    # 'django_jenkins.tasks.run_sloccount'
)

In requirements.txt for the build environement, if I say
django-jenkins==0.17
(or, until today with no version specified) my results end with
....
----------------------------------------------------------------------
Ran 5 tests in 45.196s

OK
Destroying test database for alias 'default'...
Executing django_jenkins.tasks.run_pep8...
Done

With django-jenkins==0.18 (the only change), I get an error relating to coverage
....
----------------------------------------------------------------------
Ran 5 tests in 44.305s

OK
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_jenkins/management/commands/jenkins.py", line 159, in handle
    coverage.save(tested_locations, options)
AttributeError: 'NoneType' object has no attribute 'save'

As I don't think I'm running coverage this is puzzling. I get other errors (lack of admin.py for some apps) when I use --enable-coverage. Should 

django_jenkins/management/commands/jenkins.py line 159 be indented to be within the if coverage block?

**Comment by kmmbvnr** [comment]
Thank you for report, and problem line identification. Fix released 0.18.1
