### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Reporter'

### ISSUE THREAD

**Issue by mbeacom** [kmmbvnr/django-jenkins#314]
This breaks any builds with coverage on `django-jenkins == 0.18.1`

```stacktrace
./manage.py jenkins -v 3 --pep8-exclude="*migrations*,*tests*" --coverage-exclude="*migrations*,*tests*"

Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "~/.virtualenv/drund/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "~/.virtualenv/drund/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~/.virtualenv/drund/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "~/.virtualenv/drund/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "~/.virtualenv/drund/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 62, in __init__
    for module_name in self.get_task_list()]
AttributeError: 'module' object has no attribute 'Reporter'
```

It looks like the culprit is `with_coverage.py` has no class `Reporter` instead it has `CoverageReporter`

At the end of `with_coverage.py` I added

```python
Reporter = CoverageReporter
```

And that worked.

I don't know if there is a specific reason the class is named `CoverageReporter`

The solution is either change the class name or set `Reporter = CoverageReporter`

**Comment by kmmbvnr** [comment]
#311
