### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Reporter'

### ISSUE THREAD

**Issue by mico** [kmmbvnr/django-jenkins#315]
When i try to use 'django_jenkins.tasks.with_coverage' in JENKINS_TASKS i got an error:
```
(.venv)MacBook-Pro-Artur:npoed-sso-edx mico$ ./manage.py jenkins
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mico/Documents/Projects/npoed-sso-edx/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/mico/Documents/Projects/npoed-sso-edx/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mico/Documents/Projects/npoed-sso-edx/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/mico/Documents/Projects/npoed-sso-edx/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 42, in load_command_class
    return module.Command()
  File "/Users/mico/Documents/Projects/npoed-sso-edx/.venv/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 60, in __init__
    for module_name in self.get_task_list()]
AttributeError: 'module' object has no attribute 'Reporter'
```

**Comment by kmmbvnr** [comment]
#311
