### ISSUE TITLE
Finding test locations on Python 3.3+

### ISSUE THREAD

**Issue by sergei-maertens** [kmmbvnr/django-jenkins#331]
I just ran into an error in django_jenkins where it failed to find the tested locations (as part of the management command).

Traceback:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django_jenkins/management/commands/jenkins.py", line 152, in handle
    tested_locations = self.get_tested_locations(test_labels)
  File "/var/lib/jenkins/jobs/ima-idb-develop/workspace/env/lib/python3.4/site-packages/django_jenkins/management/commands/jenkins.py", line 184, in get_tested_locations
    locations.append(os.path.dirname(app_config.module.__file__))
AttributeError: 'module' object has no attribute '__file__'
```

The underlying cause is that we forgot to create a `__init__.py` file in the root of our project app, which is [legal since Python 3.3](https://docs.python.org/3/whatsnew/3.3.html#pep-420-implicit-namespace-packages).

The offending code is:

```
    app_config = apps.get_containing_app_config(test_label)
            if app_config is not None:
                locations.append(os.path.dirname(app_config.module.__file__))
            else:
                warnings.warn('No app found for test: {0}'.format(test_label))
```

The `app_config` exists, only the module is implicit and doesn't have a `__file__` attribute. According to [PEP0420](https://www.python.org/dev/peps/pep-0420/#id24) this module has a `__path__` attribute which is an iterable of paths:

```
(BPdb) app_config.module.__path__
_NamespacePath(['/home/bbt/coding/maykin/imadb/projects'])
```

It seems to me that in that case the code should look like this:

```
for test_label in test_labels:
    app_config = apps.get_containing_app_config(test_label)
    if app_config is not None:
        try:
            locations.append(os.path.dirname(app_config.module.__file__))
        except AttributeError:  # implicit namespace package
            locations += list(app_config.module.__path__)
    else:
        warnings.warn('No app found for test: {0}'.format(test_label))
```

Thoughts?

**Comment by kmmbvnr** [comment]
Thanks for report! Seems django already done app path searching for us.

**Comment by sergei-maertens** [comment]
Even better :-)
