### ISSUE TITLE
run_flake8 now works for flake8==2.5.x

### ISSUE THREAD

**Issue by tbicr** [kmmbvnr/django-jenkins#332]
Settings:

    JENKINS_TASKS = (
        'django_jenkins.tasks.run_flake8',
    )

Error:

    Executing django_jenkins.tasks.run_flake8...
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
        super(Command, self).run_from_argv(argv)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
        super(Command, self).execute(*args, **options)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 159, in handle
        coverage.save(tested_locations, options)
      File "/home/tbicr/Project/pandadoc-api-env/local/lib/python2.7/site-packages/django_jenkins/tasks/run_flake8.py", line 98, in run
        pep8style.input_dir(os.path.relpath(location))
    AttributeError: 'StyleGuide' object has no attribute 'input_dir'

**Comment by kmmbvnr** [comment]
Have you try django-jenkins from master branch?

**Comment by tbicr** [comment]
No, 0.18 with django 1.7, look like you already fixed it in master, sorry for duplicate.
