### ISSUE TITLE
argparse.ArgumentError: argument --debug: conflicting option string: --debug

### ISSUE THREAD

**Issue by ricw** [kmmbvnr/django-jenkins#334]
Am having trouble to run this on python 3.5 with relatively standard packages (have appended the pip freeze list below). Tested on both macos as well as the docker python-3.5 image. 

There is seemingly a conflict in the "debug" parser argument. I tried to identify where exactly conflict occurs outside of django-jenkins, but couldn't find it. Neither "django.core.management.base.BaseCommand" nor "django.core.management.commands.test.Command" seem to have "debug" parser commands. Testing with "coverage .." works perfectly fine.

Tested both the latest dev version from git as well as 0.18.1 (via pip install django-jenkins). This is the error message from the dev version:

```
python manage.py jenkins
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/path/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/path/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path/venv/data_manager_jenkins/lib/python3.5/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(arg)

  File "/path/venv/data_manager_jenkins/lib/python3.5/site-packages/django/core/management/base.py", line 336, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/path/venv/lib/python3.5/site-packages/django/core/management/base.py", line 310, in create_parser
    self.add_arguments(parser)
  File "/path/venv/src/django-jenkins/django_jenkins/management/commands/jenkins.py", line 51, in add_arguments
    help='Do not intercept stdout and stderr, friendly for console debuggers'),
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1344, in add_argument
    return self._add_action(action)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1707, in _add_action
    self._optionals._add_action(action)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1548, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1358, in _add_action
    self._check_conflict(action)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1497, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1506, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --debug: conflicting option string: --debug
```

**pip freeze output**:

```
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
boto3==1.3.1
botocore==1.4.25
coverage==4.1
decorator==4.0.9
Django==1.9.6
django-extensions==1.6.7
-e git://github.com/kmmbvnr/django-jenkins.git@bf45dfa7d1ebd2c6e8f0ce0683545c001c343b68#egg=django_jenkins
django-nose==1.4.3
docutils==0.12
flake8==2.5.4
gnureadline==6.3.3
ipython==4.2.0
ipython-genutils==0.1.0
jmespath==0.9.0
mccabe==0.4.0
mock==2.0.0
nose==1.3.7
pbr==1.10.0
pep8==1.7.0
pexpect==4.1.0
pickleshare==0.7.2
psycopg2==2.6.1
ptyprocess==0.5.1
pyflakes==1.2.3
python-dateutil==2.5.3
simplegeneric==0.8.1
six==1.10.0
traitlets==4.2.1
```

**Comment by kmmbvnr** [comment]
You should not use nose with djangp-jenkins

Check your test rumner settings.
