### ISSUE TITLE
Issue while installing sloccount using npm

### ISSUE THREAD

**Issue by jinxac** [kmmbvnr/django-jenkins#344]
While running `venv/bin/python manage.py jenkins binger.tests --settings=insights.test_settings --enable-coverage` I am getting following error.

I installed on my machine using brew where it works however in my dev environment(ubuntu) I installed this npm it is showing following error.

```
Executing django_jenkins.tasks.run_sloccount...
/usr/local/lib/node_modules/sloccount/index.js:21
    throw Error('Please configure one or more src directories!')
          ^
Error: Please configure one or more src directories!
    at Error (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/sloccount/index.js:21:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/sloccount/cli.js:23:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 116, in handle
    coverage.save(tested_locations, options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django_jenkins/tasks/run_sloccount.py", line 16, in run
    raise subprocess.CalledProcessError(retcode, cmd, output='%s\n%s' % (report_output, err))
subprocess.CalledProcessError: Command '['sloccount', '--duplicates', '--wide', '--details', u'/var/lib/jenkins/jobs/InsightsDev/workspace/insights/binger']' returned non-zero exit status 8
```

Now I uninstalled the module using npm uninstall and installed sloccount using apt-get. It seems to be working fine now though I am seeing following warnings:-

`perl: warning: Falling back to the standard locale ("C").`

**Comment by kmmbvnr** [comment]
sloccount is not npm program http://www.dwheeler.com/sloccount/
