### ISSUE TITLE
Csslint throwing bad_alloc() error

### ISSUE THREAD

**Issue by jinxac** [kmmbvnr/django-jenkins#345]
I installed csslint using npm.

```
csslint

Usage: csslint-rhino.js [options]* [file|dir]*

Global Options
  --help                                   Displays this information.
  --format=<format>                        Indicate which format to use for output.
  --list-rules                             Outputs all of the rules available.
  --quiet                                  Only output when errors are present.
  --errors=<rule[,rule]+>                  Indicate which rules to include as errors.
  --warnings=<rule[,rule]+>                Indicate which rules to include as warnings.
  --ignore=<rule[,rule]+>                  Indicate which rules to ignore completely.
  --exclude-list=<file|dir[,file|dir]+>    Indicate which files/directories to exclude from being linted.
  --config=<file>                          Reads csslint options from specified file.
  --version                                Outputs the current version number.
```

Now when I use django-jenkins to run my tests its throwing error while running csslint task.

```
venv/bin/python manage.py jenkins  --settings=insights.test_settings --enable-coverage
Creating test database for alias 'default'...
/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Article.published_at received a naive datetime (2016-08-18 12:00:10.806790) while time zone support is active.
  RuntimeWarning)

/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Article.last_revision_at received a naive datetime (2016-08-18 12:00:10.806775) while time zone support is active.
  RuntimeWarning)

.
----------------------------------------------------------------------
Ran 1 test in 0.839s

OK
Destroying test database for alias 'default'...
Storing coverage info...
Executing django_jenkins.tasks.run_pep8...
Executing django_jenkins.tasks.run_pyflakes...
Executing django_jenkins.tasks.run_jshint...
Executing django_jenkins.tasks.run_csslint...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 116, in handle
    coverage.save(tested_locations, options)
  File "/var/lib/jenkins/jobs/InsightsDev/workspace/insights/venv/local/lib/python2.7/site-packages/django_jenkins/tasks/run_csslint.py", line 36, in run
    raise subprocess.CalledProcessError(retcode, cmd, output=output + '\n' + err)
TypeError: unsupported operand type(s) for +: 'instance' and 'str'
```

I tried looking into the code and saw that the process.poll() is returning back -6 instead of 0 or 1 hence the subsequent condition check if failing.

```
  process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
            process_output, err = process.communicate()
            retcode = process.poll()
```

Can you please check this once?

**Comment by kmmbvnr** [comment]
pull request with fix is welcom

**Comment by jinxac** [comment]
Sure let me check on that 👍

**Comment by kmmbvnr** [comment]
fixed
