### ISSUE TITLE
add_arguments exception

### ISSUE THREAD

**Issue by osmelyanes** [kmmbvnr/django-jenkins#348]
manage.py jenkins & manage.py jenkins --enable-coverage:
File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django_jenkins-0.19.0-py3.4.egg\django_jenkins\management\commands\jenkins.py", line 53, in add_arguments
    super(Command, self).add_arguments(parser)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\commands\test.py", line 57, in add_arguments
    "The method to extend accepted command-line arguments by the "
RuntimeError: The method to extend accepted command-line arguments by the test management command has changed in Django 1.8. Please create an add_arguments class method to achieve this.

settings.py:
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jenkins',
    ...'my_custom_apps'...)

JENKINS_TASKS = (
    'django_jenkins.tasks.run_pep8',
    'django_jenkins.tasks.run_pyflakes',
    'django_jenkins.tasks.run_pylint'
    'django_jenkins.tasks.run_jslint',
)

pip freeze:
astroid==1.4.8
colorama==0.3.7
coverage==4.2
dill==0.2.5
Django==1.8.15
django-jenkins==0.19.0
et-xmlfile==1.0.1
flake8==3.0.4
isort==4.2.5
jdcal==1.2
jslint==0.6.0
lazy-object-proxy==1.2.2
ldap3==1.4.0
lxml==3.5.0
mccabe==0.5.2
openpyxl==2.3.3
pep8==1.7.0
Pillow==3.1.1
psycopg2==2.6.1
pyasn1==0.1.9
pycharm===debug
pycodestyle==2.0.0
pycrypto==2.6.1
pyflakes==1.2.3
pylint==1.6.4
pyreadline==2.1
python-dateutil==2.5.3
python-docx==0.8.5
simplejson==3.8.2
six==1.10.0
Unidecode==0.4.19
virtualenv==15.0.1
wadofstuff-django-serializers==1.1.0
wrapt==1.10.8
xlrd==0.9.4

full exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pycharm\django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "c:\python34\Lib\runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "c:\python34\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\python34\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:/WORKSPACE/PyCharm-ExtJs/versat-erp\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django_jenkins-0.19.0-py3.4.egg\django_jenkins\management\commands\jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\commands\test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\base.py", line 382, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\base.py", line 355, in create_parser
    self.add_arguments(parser)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django_jenkins-0.19.0-py3.4.egg\django_jenkins\management\commands\jenkins.py", line 53, in add_arguments
    super(Command, self).add_arguments(parser)
  File "D:\WORKSPACE\PyCharm-ExtJs\versat-erp\virtualenv\lib\site-packages\django\core\management\commands\test.py", line 57, in add_arguments
    "The method to extend accepted command-line arguments by the "
RuntimeError: The method to extend accepted command-line arguments by the test management command has changed in Django 1.8. Please create an add_arguments class method to achieve this.

Process finished with exit code 1

**Comment by kmmbvnr** [comment]
Do you have this issue with latest django-jenkins?

**Comment by kmmbvnr** [comment]
I think upgrading to django-jenkins 0.110.0 will solves this

**Comment by osmelyanes** [comment]
The error is the same in all versions. I've tried with versions: 0.18.0, 0.19.0 and 0.110.0 from the master.
I'm using Django==1.8. Is the error related to a compatibility issue with this version? Is there anything I should try, please let me know. Thanks!

**Comment by kmmbvnr** [comment]
Do you have `JENKINS_TEST_RUNNER` settings?

**Comment by osmelyanes** [comment]
The error persist and is the same, no matters what I put inside JENKINS_TEST_RUNNER var.
I didn't have it from the beginning but I added:
JENKINS_TEST_RUNNER = (
    'TestRunner'
)

**Comment by kmmbvnr** [comment]
You have to debug what is the source of `option_list` attribute in your test runner, b/c django-jenkins have not used `option_list` for a while

https://github.com/django/django/blob/stable/1.8.x/django/core/management/commands/test.py#L53
