### ISSUE TITLE
django-jenkins does not work with django 1.11

### ISSUE THREAD

**Issue by bernieke** [kmmbvnr/django-jenkins#355]
I get the following traceback:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.4/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.4/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.4/dist-packages/django_jenkins/management/commands/jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/lib/python3.4/dist-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/lib/python3.4/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.4/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.4/dist-packages/django_jenkins/management/commands/jenkins.py", line 104, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/lib/python3.4/dist-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/usr/lib/python3.4/dist-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/usr/lib/python3.4/dist-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/usr/lib/python3.4/dist-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/usr/lib/python3.4/dist-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3.4/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.4/dist-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.load_disk()
  File "/usr/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 82, in load_disk
    module = import_module(module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'django.contrib.auth.migrations_not_used_in_tests'
```

**Comment by bernieke** [comment]
Never mind, it was our own code adding the migrations_not_used_in_tests stuff. I've changed this by using MIGRATE in the DATABASES settings instead, and it's working again now.

**Comment by manjitkumar** [comment]
I am facing a problem with django 1.11 with python3.6 `ModuleNotFoundError: No module named 'django-jenkins'` though I have installed it as per given in readme.

```python
» ./manage.py jenkins --enable-coverage
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/manjit/.virtualenvs/crate-api/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/manjit/.virtualenvs/crate-api/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/manjit/.virtualenvs/crate-api/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/manjit/.virtualenvs/crate-api/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/manjit/.virtualenvs/crate-api/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/Users/manjit/.virtualenvs/crate-api/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-jenkins'
```
